[package]
name = "webringer"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["http2", "http1", "query", "form"] }
clap = { version = "4.5.36", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio"] }
tokio = "1.44.2"
tower-http = { version = "0.6.2", features = ["fs"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
