[package]
name = "webringer"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.3", features = ["http2"] }
clap = { version = "4.5.36", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["sqlite"] }
tokio = "1.44.2"
